### ISSUE TITLE
Add an entity for arming/disarming the alarm

### ISSUE THREAD

**Issue by nshp** [borski/ha-lucidmotors#6]
Maybe an AlarmControlPanel entity if that's not too overkill

**Comment by borski** [comment]
Added in https://github.com/borski/ha-lucidmotors/commit/5f6d5d1e653167c7556e49251e63dce6c75baa22. The underlying library doesn't have a definition for how to set the mode to silent/not silent yet, but that's the last step for this issue.

**Comment by borski** [comment]
Done, actually, in https://github.com/borski/ha-lucidmotors/commit/c3b73857941503a5f15c680adf4c86c2bf1811ee

Alarm control, as it turns out, take a mode, not a state - and that mode can be one of 'on', 'off', or 'silent' - where silent is the 'push notifications only' alarm mode you can set on the app. Setting any of them correctly sets the state in the mobile app, and it updates based on the state at every update interval. Pretty neat, actually.
